---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: skylab-crossplane-cluster

resources:
  - manifests/composition.yaml

labels:
- includeSelectors: true
  pairs:
    environment: dev
    cluster-type: eks
    cluster-name: skylab
    managed-by: crossplane
    layer: infra
    component: crossplane

namespace: crossplane-system

patches:
  - target:
      kind: Composition
      name: skylab-eks-cluster
    patch: |-
      - op: add
        path: /metadata/labels/backstage.io~1managed-by
        value: template