---
site_name: 'Skylab EKS Cluster'
site_description: 'Documentation for skylab EKS cluster infrastructure'

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Operations: operations.md
  - Troubleshooting: troubleshooting.md

plugins:
  - techdocs-core

theme:
  name: material
  palette:
    primary: green
    accent: black
