

---
apiVersion: infrastructure.skylab.com/v1alpha1
kind: XClusterRBAC
metadata:
  name: skylab-rbac
  namespace: crossplane-skylab
  labels:
    environment: dev
    cluster-type: eks
    cluster-name: skylab
    managed-by: backstage-template
    template: eks-cluster-crossplane
    component: rbac
  annotations:
    backstage.io/managed-by-location: url:https://github.com/SkylarHoughtonGithub/skylab-backstage-configs/blob/main/dev/eks/skylab/infra/crossplane/catalog-info.yaml
    template.backstage.io/created-by: skylab-eks-cluster-template
spec:
  clusterName: skylab-dev
  environment: dev