
---
apiVersion: infrastructure.skylab.com/v1alpha1
kind: XEKSAccessEntries
metadata:
  name: skylab-access
  namespace: crossplane-skylab
  labels:
    environment: dev
    cluster-type: eks
    cluster-name: skylab
    managed-by: backstage-template
    template: eks-cluster-crossplane
    component: access
  annotations:
    backstage.io/managed-by-location: url:https://github.com/SkylarHoughtonGithub/skylab-backstage-configs/blob/main/dev/eks/skylab/infra/crossplane/catalog-info.yaml
    template.backstage.io/created-by: skylab-eks-cluster-template
spec:
  clusterName: skylab-dev
  region: us-east-2
  awsAccountId: "635314249418"
  adminPrincipals:
    - name: chicken
      type: user
      kubernetesGroups: ["system:masters"]